# Generated by Django 5.1.2 on 2024-10-31 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_group_rename_created_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 31, 20, 43, 14, 877393, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
