# Generated by Django 5.1.2 on 2024-11-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_group_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='group',
        ),
        migrations.CreateModel(
            name='SubprojectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproject_groups', to='projects.subproject')),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='subproject_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='projects.subprojectgroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
