# Generated by Django 5.1.2 on 2024-11-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_snippet_group_subprojectgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='subproject_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='projects.subprojectgroup'),
        ),
    ]
