# Generated by Django 4.2.16 on 2024-12-02 21:10

from django.conf import settings
from django.db import migrations, models
import projects.enums.note_visibility


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_note_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text="Users who can view this note if visibility is set to 'shared'.", related_name='shared_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Publica'), ('PRIVATE', 'Privada'), ('SHARED', 'Compartida')], default=projects.enums.note_visibility.NoteVisibility['PRIVATE'].value, max_length=10),
        ),
    ]
