services:
  db:
    image: postgres
    container_name: guardamelo_api_db
    environment:
      - POSTGRES_DB=guardamelo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql:/sql
    expose:
      - '5432'
  web:
    build: .
    container_name: guardamelo_api_web
    env_file:
      - .env
    command: sh run.sh
    ports:
      - 8000:8000
      - 8888:8888
    volumes:
      - .:/app
    depends_on:
      - db