# Generated by Django 4.2.16 on 2024-11-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
